# Generated by Django 3.0 on 2019-12-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Tipo de Articulo')),
            ],
            options={
                'verbose_name': 'Tipo de Articulo',
                'verbose_name_plural': 'Tipos de Articulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('costo', models.FloatField(verbose_name='Costo')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('existencia', models.IntegerField(verbose_name='Existencia')),
                ('TipoArticulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consignacion.TipoArticulo')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['nombre'],
            },
        ),
    ]
