# Generated by Django 3.0 on 2019-12-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Vendedor')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('dui', models.CharField(max_length=15, verbose_name='D.U.I.')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('credito', models.FloatField(verbose_name='Limite de Credito')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre'],
            },
        ),
    ]
