# Generated by Django 3.0 on 2019-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0002_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
