# Generated by Django 3.0 on 2019-12-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0003_auto_20191231_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='credito',
        ),
    ]
