# Generated by Django 3.0 on 2020-01-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0005_auto_20191231_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consigna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_recibe', models.DateField(blank=True, null=True, verbose_name='Fecha Recibe')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('viatico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Viatico')),
                ('panalizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Penalizacion')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('completa', models.BooleanField(verbose_name='Consigna Completa')),
            ],
            options={
                'verbose_name': 'Consigna',
                'verbose_name_plural': 'Consignas',
                'ordering': ['id', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('dui', models.CharField(max_length=15, verbose_name='D.U.I.')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_cliente',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Precio Cliente'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='DetalleConsigna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Articulo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignacion.Articulo')),
                ('consigna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignacion.Consigna')),
            ],
            options={
                'verbose_name': 'Detalle de Consigna',
                'verbose_name_plural': 'Detalle de Consignas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='consigna',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consignacion.Gestor'),
        ),
        migrations.AddField(
            model_name='consigna',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consignacion.Vendedor'),
        ),
    ]
