# Generated by Django 3.0 on 2020-01-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0006_auto_20200101_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='consigna',
            name='panalizacion',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Penalizacion'),
        ),
        migrations.AlterField(
            model_name='consigna',
            name='viatico',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Viatico'),
        ),
    ]
