# Generated by Django 3.0 on 2020-01-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0008_auto_20200101_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleconsigna',
            name='consigna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consignacion.Consigna'),
        ),
    ]
