# Generated by Django 3.0 on 2020-01-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0009_auto_20200101_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Articulo', 'verbose_name_plural': 'Tipos de Articulos'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='existencia',
            field=models.IntegerField(default=0, verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='detalleconsigna',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
