# Generated by Django 3.0 on 2020-01-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignacion', '0010_auto_20200106_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consigna',
            old_name='panalizacion',
            new_name='penalizacion',
        ),
    ]
